spring.application.name=complaintbox

# ---------- MySQL ----------
# createDatabaseIfNotExist=true creates complaintbox_db automatically if it is missing
spring.datasource.url=jdbc:mysql://localhost:3306/complaintbox_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=irfan2008


# ---------- JPA / Hibernate ----------
# "update" creates / updates the tables automatically
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ---------- Errors ----------
# Never show stack traces to the client
server.error.include-stacktrace=never
